---
title: "blt_file"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(unpivotr)
library(htmltools)
library(tidyverse)

link<-"https://www.dvcrequest.com/point-chart/bay_lake_towers_2020.html"

```


```{r}
hlink<- read_html(link)

table<-hlink %>% html_nodes("table") %>% 
  html_table(header=F,fill=T)

table <- table[[1]]
table
#add the table to a dataframe
dict <- as.data.frame(table)
View(dict)
```


```{r}
cells <- as_cells(table)
View(cells)
```


```{r}
(cells<-cells %>% filter(col>2,row>1) %>% select(-data_type))
```




```{r}
cellstemp<-
   cells %>% spread(row,chr) %>% filter(!col %in% c('6','10','14'))


room_view<-cellstemp[,2:3]
#seasons
adventure<-cellstemp[,4:6]
choice<-cellstemp[,7:9]
dream<-cellstemp[,10:12]
magic<-cellstemp[,13:15]
premier<-cellstemp[,16:18]

adventure<-cbind(room_view,adventure)
choice<-cbind(room_view,choice)
dream<-cbind(room_view,dream)
magic<-cbind(room_view,magic)
premier<-cbind(room_view,premier)

dfs<-data.frame(Map(c,adventure,choice,dream,magic,premier))

dfs
```


```{r}
dfs<-dfs %>% rename_at(c(1,2,3,4,5),~c("room","view","season","Sun_Th","Fri_Sat")) %>%
  mutate_at(vars('Sun_Th','Fri_Sat'),as.character) %>%
  mutate_at(vars('Sun_Th','Fri_Sat'),as.numeric)

(dfl<-dfs %>% gather("weekday", "points",Sun_Th:Fri_Sat))

```


```{r}
dfl$room<-as.character(dfl$room)
head(dfl)
```


```{r}
#change naming of room type
dfl[dfl$room == "STUDIO(Sleeps up to 4)","room"] = "Studio"
dfl[dfl$room == "1-BEDROOM\r\n      VACATION HOME(Sleeps up to 5)","room"] = "1-Bedroom"
dfl[dfl$room == "2-BEDROOM\r\n      VACATION HOME(Sleeps up to 9)","room"] = "2-Bedroom"
dfl[dfl$room == "3-BEDROOM\r\n  GRAND VILLA(Sleeps up to 12)","room"] = "3-Bedroom"

```


```{r}
dfl %>%
  ggplot(aes(x=fct_reorder(room,points),y=points,fill=fct_reorder(view,points)))+geom_boxplot()+scale_fill_brewer(palette= "OrRd")
```

```{r}
dfl %>%
  ggplot(aes(x=fct_reorder(season,points),y=points,fill=fct_reorder(view,points)))+geom_boxplot()+scale_fill_brewer(palette= "OrRd")
```
room type determines points more than season (less variability)

```{r}
dfl %>% filter(room %in% c("Studio", "1-Bedroom")) %>%
  group_by(room, season) %>% summarize(avg_point = mean(points)) %>% ungroup() %>%
  ggplot(aes(
    x = fct_reorder(season, avg_point),
    y = avg_point,
    group = room
  )) + geom_col(aes(fill = room), position = "dodge") + geom_text(aes(label =
                                                                        round(avg_point, 1)),
                                                                  position = position_dodge(0.9),
                                                                  vjust = 0) +
  scale_fill_manual(values = c("skyblue", "grey"))
```

```{r}
df20<-dfl %>% mutate(resort="BLT")
df20%>% saveRDS(file = "BLT2020.rds")
